function(qhenkix_mark_dependency_targets_in_directory _qhenkix_dir)
    get_property(_qhenkix_targets DIRECTORY "${_qhenkix_dir}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(_qhenkix_target IN LISTS _qhenkix_targets)
        set_property(TARGET ${_qhenkix_target} PROPERTY FOLDER "_Dependencies")
        if(CMAKE_GENERATOR MATCHES "Visual Studio")
            set_property(TARGET ${_qhenkix_target} PROPERTY EXCLUDE_FROM_DEFAULT_BUILD TRUE)
        endif()
    endforeach()

    get_property(_qhenkix_subdirs DIRECTORY "${_qhenkix_dir}" PROPERTY SUBDIRECTORIES)
    foreach(_qhenkix_subdir IN LISTS _qhenkix_subdirs)
        qhenkix_mark_dependency_targets_in_directory("${_qhenkix_subdir}")
    endforeach()
endfunction()

function(qhenkix_add_dependency_subdirectory source_dir binary_dir)
    add_subdirectory(${source_dir} ${binary_dir} ${ARGN})
    qhenkix_mark_dependency_targets_in_directory("${binary_dir}")
endfunction()

function(qhenkix_add_subdirectory_with_build_shared_libs source_dir binary_dir build_shared_libs)
    set(_qhenkix_prev_build_shared_libs "")
    if(DEFINED BUILD_SHARED_LIBS)
        set(_qhenkix_prev_build_shared_libs "${BUILD_SHARED_LIBS}")
    endif()

    set(BUILD_SHARED_LIBS "${build_shared_libs}")
    qhenkix_add_dependency_subdirectory(${source_dir} ${binary_dir} ${ARGN})

    if(_qhenkix_prev_build_shared_libs STREQUAL "")
        unset(BUILD_SHARED_LIBS)
    else()
        set(BUILD_SHARED_LIBS "${_qhenkix_prev_build_shared_libs}")
    endif()
endfunction()
