name: QhenkiX

on:
  push:
    branches:
      - 'release/**'
      - main
  pull_request:
    branches:
      - 'release/**'
      - main
  merge_group:

jobs:
  build-qhenkix:
    name: QhenkiX
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29'

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Configure CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

    - name: Build QhenkiX
      run: cmake --build build --config Release --target QhenkiX

    - name: Upload QhenkiX Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qhenkix-library-windows
        path: |
          build/QhenkiX/Release/
          QhenkiX/include/
        retention-days: 1

  build-sxc:
    name: SXC
    runs-on: windows-latest
    needs: build-qhenkix
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.18'

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Download QhenkiX
      uses: actions/download-artifact@v4
      with:
        name: qhenkix-library-windows
        path: QhenkiX/

    - name: Configure CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

    - name: Build SXC
      run: cmake --build build --config Release --target SXC

    - name: Upload SXC Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sxc-windows
        path: build/SXC/Release/
        retention-days: 1

  build-examples:
    name: ${{ matrix.example }}
    runs-on: windows-latest
    needs: build-qhenkix
    strategy:
      matrix:
        example: [SimpleExample, ImGuiExample, gltfViewer]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.18'

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Download QhenkiX
      uses: actions/download-artifact@v4
      with:
        name: qhenkix-library-windows
        path: QhenkiX/

    - name: Configure CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

    - name: Build ${{ matrix.example }}
      run: cmake --build build --config Release --target ${{ matrix.example }}

    - name: Upload ${{ matrix.example }} Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.example }}-build-windows
        path: build/Examples/${{ matrix.example }}/Release/
        retention-days: 1